include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = make_c_interface

make_c_interface_OBJC_FILES = \
							  AGSParser.m\
	make_c_interface.m

make_c_interface_CPPFLAGS = -I../../base/Source

CC=clang

include $(GNUSTEP_MAKEFILES)/tool.make

