.SUFFIXES: .c .obj

.SILENT:

include common.mk

OBJECTS = $(COREBASE_C_FILES:.c=.obj)

OBJ_CFLAGS = -MT

all: $(OBJECTS)
	link $(OBJECTS) $(LINKFLAGS) \
	  /DEFAULTLIB:icuin /DEFAULTLIB:icuuc /DLL /OUT:gnustep-corebase.dll

.c.obj:
	$(CC) $(ADDITIONAL_INCLUDE_DIRS) $(OBJ_CFLAGS) $(ADDITIONAL_CFLAGS) \
          $(CFLAGS) -c $<

clean:
	del *.obj
	del gnustep-corebase.dll
	del gnustep-corebase.exp
	del gnustep-corebase.lib