name: Apple Foundation Reference

# Runs the CoreBase Test suite with against Apples (Core)Foundation.
# We want our behavior to match. Test files may be excluded by setting
# the APPLE_SKIP_TESTS environment variable.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos:
    name: macOS Apple CoreFoundation tests
    runs-on: macos-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Run Apple compatibility tests
        run: ./.github/scripts/run-apple-tests.py
